oe_theme.settings:
  type: theme_settings
  label: 'OpenEuropa Theme settings'
  mapping:
    component_library:
      type: string
      label: 'ECL component library, either EC or EU'
    template:
      type: string
      label: 'ECL templates, either Core or Standardised'
